version: '3'
services:
  server:
    container_name: movies-app
    build: .
    restart: always
    environment:
      MONGO_SERVER_ADDR: db
    volumes:
      - './:/app'
      - './:/app/node_modules'
    depends_on:
      - db
    links:
      - db
    ports:
      - '3001:3001'
    
  db:
    image: mongo
    container_name: movies-db
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
    command: '--quiet'
